project:
  type: website

website:
  title: "Plant Ecology UCT"
  favicon: assets/icon.png
  twitter-card: true
  opengraph: true
  site-url: https://www.myblogexample.io
  description: "Research lab in the Department of Biological Sciences at the University of Cape Town"
  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/jslingsby/PlantEcology
  repo-actions: [edit, issue]
  navbar:
    background: light
    foreground: secondary
    search: true
    right:
      - href: about.qmd
        text: About
      - href: news/index.qmd
        text: News
      - href: projects/index.qmd
        text: Projects
      - href: teaching/index.qmd
        text: Teaching
      - href: lab/index.qmd
        text: Lab
      - href: https://github.com/PlantEcologi
        icon: "github"
      - href: https://twitter.com/JasperSlingsby
        icon: "twitter"
      - href: https://scholar.google.com/citations?user=ZjBauSkAAAAJ&hl=en
        icon: "mortarboard-fill"
      - icon: rss
        href: index.xml

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    smooth-scroll: true

editor: visual

